package com.anshika.calories;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
  LinearLayout root, logBox; TextView calories, burn, balance, steps, weight; android.content.SharedPreferences p;
  int in,burned,stepCount; float kg; final int target=1350;
  int mint=Color.rgb(231,246,240), peach=Color.rgb(255,241,231), teal=Color.rgb(42,174,145), ink=Color.rgb(30,48,44);
  public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("tracker",0);load();build();}
  TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(ink);v.setPadding(8,8,8,8);if(bold)v.setTypeface(null,1);return v;}
  GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
  void build(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,26,28,36);root.setBackgroundColor(Color.rgb(250,250,246));sc.addView(root);setContentView(sc);
    LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.HORIZONTAL);hero.setGravity(Gravity.CENTER_VERTICAL);hero.setBackground(bg(mint,40));hero.setPadding(24,22,24,22);ImageView im=new ImageView(this);im.setImageResource(com.anshika.calories.R.drawable.anshika_logo);im.setScaleType(ImageView.ScaleType.CENTER_CROP);hero.addView(im,new LinearLayout.LayoutParams(120,120));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(18,0,0,0);ht.addView(tv("Hi, Anshika 👋",24,true));ht.addView(tv("Your calorie-deficit dashboard",14,false));hero.addView(ht);root.addView(hero,new LinearLayout.LayoutParams(-1,-2));
    root.addView(tv("Today",22,true)); LinearLayout cards=new LinearLayout(this);cards.setOrientation(LinearLayout.VERTICAL);root.addView(cards);
    calories=metric(cards,"Calories In",in+" / "+target+" kcal",peach);burn=metric(cards,"Forfeit / Burn",burned+" kcal",mint);balance=metric(cards,"Actual balance",balanceText(),Color.rgb(245,238,255));steps=metric(cards,"Steps",stepCount+"",Color.rgb(238,247,255));weight=metric(cards,"Weight",kg>0?kg+" kg":"Add weight",Color.rgb(255,247,221));
    LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setGravity(Gravity.CENTER);root.addView(tv("Quick actions",20,true));root.addView(actions);button(actions,"+ Food",()->input("Add food calories","kcal",v->{in+=v;save();refresh();addLog("Food +"+v+" kcal");}));button(actions,"+ Burn",()->input("Add burned calories","kcal",v->{burned+=v;save();refresh();addLog("Burn +"+v+" kcal");}));button(actions,"+ Steps",()->input("Add steps","steps",v->{stepCount+=v;save();refresh();addLog("Steps +"+v);}));
    button(root,"Log weight",()->inputFloat()); root.addView(tv("Today's log",20,true));logBox=new LinearLayout(this);logBox.setOrientation(LinearLayout.VERTICAL);logBox.setBackground(bg(Color.WHITE,32));logBox.setPadding(18,12,18,12);root.addView(logBox);renderLog();
    root.addView(tv("Forfeit/Burn is an estimate. Real fat change depends on total daily energy expenditure, not exercise alone.",12,false)); }
  TextView metric(LinearLayout parent,String title,String value,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(22,16,22,16);c.setBackground(bg(color,30));TextView t=tv(title,13,false),v=tv(value,22,true);c.addView(t);c.addView(v);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,8,0,8);parent.addView(c,lp);return v;}
  void button(ViewGroup parent,String text,Runnable r){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(bg(teal,28));b.setOnClickListener(v->r.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(parent instanceof LinearLayout&&((LinearLayout)parent).getOrientation()==LinearLayout.HORIZONTAL?0:-1,-2,parent instanceof LinearLayout&&((LinearLayout)parent).getOrientation()==LinearLayout.HORIZONTAL?1:0);lp.setMargins(5,8,5,8);parent.addView(b,lp);}
  interface IntCb{void go(int v);} void input(String title,String hint,IntCb cb){EditText e=new EditText(this);e.setInputType(2);e.setHint(hint);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Add",(d,w)->{try{cb.go(Integer.parseInt(e.getText().toString()));}catch(Exception x){}}).setNegativeButton("Cancel",null).show();}
  void inputFloat(){EditText e=new EditText(this);e.setInputType(8194);e.setHint("kg");new AlertDialog.Builder(this).setTitle("Today's weight").setView(e).setPositiveButton("Save",(d,w)->{try{kg=Float.parseFloat(e.getText().toString());save();refresh();addLog("Weight "+kg+" kg");}catch(Exception x){}}).setNegativeButton("Cancel",null).show();}
  String balanceText(){int estimatedTdee=1700+Math.max(0,burned);int bal=in-estimatedTdee;return bal<=0?Math.abs(bal)+" kcal estimated deficit":bal+" kcal estimated surplus";}
  void refresh(){calories.setText(in+" / "+target+" kcal");burn.setText(burned+" kcal");balance.setText(balanceText());steps.setText(stepCount+"");weight.setText(kg>0?kg+" kg":"Add weight");}
  String key(){return new SimpleDateFormat("yyyyMMdd",Locale.US).format(new Date());} void load(){String k=key();in=p.getInt(k+"in",0);burned=p.getInt(k+"burn",0);stepCount=p.getInt(k+"steps",0);kg=p.getFloat("weight",0);}
  void save(){String k=key();p.edit().putInt(k+"in",in).putInt(k+"burn",burned).putInt(k+"steps",stepCount).putFloat("weight",kg).apply();}
  void addLog(String s){String k=key()+"log";String old=p.getString(k,"");p.edit().putString(k,s+"\n"+old).apply();renderLog();}
  void renderLog(){if(logBox==null)return;logBox.removeAllViews();String s=p.getString(key()+"log","");if(s.isEmpty())logBox.addView(tv("No entries yet",14,false));else for(String x:s.split("\\n"))if(!x.isEmpty())logBox.addView(tv("• "+x,14,false));}
}
